version: "3"
services:
  data_division:
    container_name: data_division
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: "prod"
    ports:
      - "8090:8090"
      - "9090:9090"
      - "9091:9091"
      - "9092:9092"
    networks:
      - br_app

networks:
  br_app:
    external: true
