version: "3"
services:
  dev-back-blue:
    container_name: tcp-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: "prod"
    ports:
      - "8050:8050"
      - "9997:9997"
      - "9998:9998"
      - "9999:9999"
    networks:
      - br_log
      - br_app

networks:
  br_log:
    external: true
  br_app:
    external: true
