version: "3"
services:
  dev-back-blue:
    container_name: dataDivision
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: "prod"
    ports:
      - "8090:8090"
      - "9997:9997"
      - "9998:9998"
      - "9999:9999"
    networks:
      - br_app

networks:
  br_app:
    external: true
