spring:
  datasource:
    username: root
    password: 12wq

  influxdb:
    username: semse
    password: semse201!
    token: EBOQzZOcOV8XTh3z_B7ZW1k8hLw54-VN10YlhrCbnejZFPuUuFGvllz1RDRt6zdHaL-J7EYae5RoHonvyBQpPg==