spring:
  profiles:
    active: local, secret

  jpa:
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
